import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { redirect } from 'next/navigation';
import { routing } from '@/i18n/routing';

import {
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import AppSidebar from '@/components/AppSidebar';
import ToggleLang from '../actions/client/ToggleLang';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const yekan = localFont({
  src: [
    {
      path: '../fonts/YekanBakh-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-yekan',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  //

  const { locale } = await params;

  if (!routing.locales.includes(locale as 'en' | 'de' | 'fa')) {
    // return notFound();
    return redirect('/');
  }

  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'fa' ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${
          yekan.variable
        } ${
          locale === 'fa' ? 'font-yekan' : 'font-geist'
        }  antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <SidebarProvider>
            <AppSidebar locale={locale} />
            <main className="p-4 w-full">
              <div className="flex justify-between ">
                <SidebarTrigger />
                <ToggleLang local={locale} />
              </div>
              {children}
            </main>
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
